routes/dashboard.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\ManagerController;
use App\Http\Controllers\Dashboard\dashboardAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard/login',[dashboardAuthController::class,'login']);
Route::post('/dashboard/login',[dashboardAuthController::class,'authenticate']);


Route::get('/forget', function () {
    return view('dashboard.authentication.forget');
})->name('forget');

Route::prefix("admin")->group(function () {


    Route::get('/', function () {
        return view('dashboard.index');
    })->name('dashboard');

//
    Route::get('/cars', function () {
        return view('dashboard.cars.index');
    })->name('cars');

    Route::get('/cars/create', function () {
        return view('dashboard.cars.create');
    })->name('new-car');

//
    Route::get('/brands', function () {
        return view('dashboard.brands.index');
    })->name('brands');

    Route::get('/brands/create', function () {
        return view('dashboard.brands.create');
    })->name('new-brand');

//
    Route::get('/taxes', function () {
        return view('dashboard.taxes.index');
    })->name('taxes');

    Route::get('/taxes/create', function () {
        return view('dashboard.taxes.create');
    })->name('new-tax');

//
    Route::get('/branches', function () {
        return view('dashboard.branches.index');
    })->name('branches');

    Route::get('/branches/create', function () {
        return view('dashboard.branches.create');
    })->name('new-branches');

//
    Route::get('/pages', function () {
        return view('dashboard.pages.index');
    })->name('pages');

    Route::get('/pages/create', function () {
        return view('dashboard.pages.create');
    })->name('new-page');

//
    Route::get('/users', function () {
        return view('dashboard.users.index');
    })->name('users');

    Route::get('/users/create', function () {
        return view('dashboard.users.create');
    })->name('new-user');
//
    Route::get('/orders', function () {
        return view('dashboard.orders.index');
    })->name('orders');

    Route::get('/orders/show', function () {
        return view('dashboard.orders.show');
    })->name('view-order');
//
    Route::get('/contacts', function () {
        return view('dashboard.contacts.index');
    })->name('contacts');

    Route::get('/contacts/show', function () {
        return view('dashboard.contacts.show');
    })->name('view-contact');
//


//    Route::get('/managers',[ManagerController::class,'index'])->name('managers');
//    Route::get('/managers/{manager}/edit',[ManagerController::class,'edit']);
//    Route::put('/managers/{manager}',[ManagerController::class,'update']);
//    Route::get('/managers/create',[ManagerController::class,'create'])->name('new-manager');
//    Route::post('/managers',[ManagerController::class,'store']);
//    Route::get('/managers/{manager}',[ManagerController::class,'show']);
//    Route::delete('/managers/{manager}',[ManagerController::class,'destroy']);


    Route::resource('managers', ManagerController::class);


});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Manager.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Manager extends Model
{
    use HasFactory;
    //protected $guarded=[];
    //protected $fillable = ['username','first-name','last-name','phone','email','password','image'];
}

app/Http/Controllers/Dashboard/ManagerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Manager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        return view('dashboard.managers.index', [
//            'managers' => Manager::all()
//        ]);

        $managers = Manager::latest()->get();
        return view('dashboard.managers.index', compact('managers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.managers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Manager $manager)
    {
        $attributes = request()->validate([
            'username' => 'required|unique:managers,username,' . $manager->id . ',id',
            'first_name' => 'required',
            'last_name' => 'required',
            'phone' => 'required',
            'email' => 'required|unique:managers,email,' . $manager->id . ',id',
            'password' => 'required|confirmed',
            'avatar' => ['nullable', 'mimes:jpg,jpeg,png,gif', 'max:2048'],
        ]);

        $avatarPath = null;
        if (request()->hasFile('avatar')) {

            $avatarName = pathinfo(request()->file('avatar')->getClientOriginalName(), PATHINFO_FILENAME);
            $avatarExt = request()->file('avatar')->getClientOriginalExtension();
            $avatarNewName = $avatarName . '-' . uniqid() . '.' . $avatarExt;

            $avatarPath = request()->file('avatar')->storeAs(
                'uploads/managers',
                $avatarNewName,
                'public',
            );
            $attributes['avatar'] = $avatarPath;
        }

//        $attributes['password'] = bcrypt($attributes['password']);
        $attributes['password'] = Hash::make(request('password'));

        Manager::create($attributes);

        return redirect('admin/managers')->with('message', 'Manger added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Manager $manager)
    {
        return view('dashboard.managers.show', compact('manager'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Manager $manager)
    {
        //($manager);
        return view('dashboard.managers.edit', ['manager' => $manager]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Manager $manager)
    {
        //dd(request());
        $attributes = request()->validate([
            'username' => 'required',
            'first_name' => 'required',
            'last_name' => 'required',
            'phone' => 'required',
            'email' => 'required|unique:managers,email,' . $manager->id . ',id',
            'avatar' => ['nullable', 'mimes:jpg,jpeg,png,gif', 'max:2048'],
        ]);

        $avatarPath = null;

        if (request()->hasFile('avatar')) {

            $avatarName = pathinfo(request()->file('avatar')->getClientOriginalName(), PATHINFO_FILENAME);
            $avatarExt = request()->file('avatar')->getClientOriginalExtension();
            $avatarNewName = $avatarName . '-' . uniqid() . '.' . $avatarExt;

            $avatarPath = request()->file('avatar')->storeAs(
                'uploads/managers',
                $avatarNewName,
                'public',
            );

        }
        $attributes['avatar'] = $avatarPath;

        if (request('password')) {
//            $attributes['password'] = bcrypt($attributes['password']);
            $attributes['password'] = Hash::make(request('password'));
        }

        $manager->update($attributes);
        return redirect('admin/managers')->with('message', 'Manger updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Manager $manager)
    {
        if (is_file($manager->avatar)) unlink($manager->avatar);
        $manager->delete();
        return back();
    }

}

resources/views/dashboard/managers/edit.blade.php
<x-dashboard.layout>
    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-4 subheader-solid"
         id="kt_subheader">
        <div
            class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-2">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">تعديل مدير - {{$manager->username}}</h5>
                <!--end::Page Title-->
                <!--begin::Actions-->
                <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="" class="text-muted">الإدارة</a>
                    </li>

                </ul>
                <!--end::Actions-->
            </div>
            <!--end::Info-->

        </div>
    </div>
    <!--end::Subheader-->

    <x-dashboard.wrap>

        <!--begin::Card-->
        <div class="card ">
            <form method="post"
                  action="{{route('managers.update',$manager->id)}}"
                  enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <!--begin::Card body-->
                <div class="card-body">

                        <!--begin::Row-->
                        <div class="row justify-content-center">
                            <div class="col-xl-7 my-2">
                                <h4 class="card-label font-size-lg font-weight-bolder text-dark mb-10">بيانات المدير
                                    :</h4>
                                <!--end::Row-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">الصورة الشخصية</label>
                                    <div class="col-9">
                                        <div class="image-input image-input-outline"
                                             id="kt_image"
                                             style="background-image: url({{asset('dashboard/assets/media/users/blank.png') }})">
                                            <div class="image-input-wrapper"
                                                 style="background-image: url('{{$manager->avatar ? asset('storage/'.$manager->avatar) : asset('dashboard/assets/media/users/blank.png') }}')"></div>

                                            <label
                                                class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                                data-action="change"
                                                data-toggle="tooltip"
                                                title=""
                                                data-original-title="Change avatar">
                                                <i class="fa fa-pen icon-sm text-muted"></i>
                                                <input type="file"
                                                       name="avatar"
                                                       accept=".png, .jpg, .jpeg"/>

                                            </label>

                                            <span
                                                class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                                data-action="cancel"
                                                data-toggle="tooltip"
                                                title="Cancel avatar">
  <i class="ki ki-bold-close icon-xs text-muted"></i>
 </span>

                                            <span
                                                class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                                                data-action="remove"
                                                data-toggle="tooltip"
                                                title="Remove avatar">
  <i class="ki ki-bold-close icon-xs text-muted"></i>
 </span>
                                        </div>
                                    </div>

                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">الأسم المستخدم</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid"
                                               type="text"
                                               name="username"

                                               value="{{$manager->username}}">
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">الأسم الاول</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid"
                                               type="text"
                                               name="first_name"
                                               value="{{$manager->first_name}}">
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">الاسم الاخير</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid"
                                               type="text"
                                               name="last_name"
                                               value="{{$manager->last_name}}">
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">الجوال</label>
                                    <div class="col-9">
                                        <div class="input-group input-group-lg input-group-solid">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="la la-phone"></i></span>
                                            </div>
                                            <input type="text" class="form-control form-control-lg form-control-solid"
                                                   value="{{$manager->phone}}"
                                                   name="phone"
                                                   placeholder="الجوال">
                                        </div>
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">البريد الالكترونى</label>
                                    <div class="col-9">
                                        <div class="input-group input-group-lg input-group-solid">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="la la-at"></i></span>
                                            </div>
                                            <input type="email"
                                                   class="form-control form-control-lg form-control-solid"
                                                   value="{{$manager->email}}"
                                                   name="email"
                                                   placeholder="البريد الالكترونى">
                                        </div>
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">كلمة المرور</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid"
                                               type="password"
                                               name="password"
                                               value="">
                                    </div>
                                </div>
                                <!--end::Group-->
                                <!--begin::Group-->
                                <div class="form-group row">
                                    <label class="col-form-label col-3 text-lg-left text-left">تاكيد كلمة المرور</label>
                                    <div class="col-9">
                                        <input class="form-control form-control-lg form-control-solid"
                                               type="password"
                                               name="password_confirmation"
                                               value="">
                                    </div>
                                </div>
                                <!--end::Group-->
                            </div>
                        </div>
                        <!--end::Row-->

                </div>
                <!--begin::Card body-->

                <div class="card-footer bg-gray-100">
                    <button type="submit"
                            class="btn btn-primary btn-block font-weight-bolder">
                        حفظ
                    </button>
                </div>
            </form>
        </div>
        <!--end::Card-->

    </x-dashboard.wrap>

    @push('scripts')

        <script>
            var avatar = new KTImageInput('kt_image');

            avatar.on('cancel', function (imageInput) {
                swal.fire({
                    title: 'Image successfully canceled !',
                    type: 'success',
                    buttonsStyling: false,
                    confirmButtonText: 'Awesome!',
                    confirmButtonClass: 'btn btn-primary font-weight-bold'
                });
            });

            avatar.on('change', function (imageInput) {
                swal.fire({
                    title: 'Image successfully changed !',
                    type: 'success',
                    buttonsStyling: false,
                    confirmButtonText: 'Awesome!',
                    confirmButtonClass: 'btn btn-primary font-weight-bold'
                });
            });

            avatar.on('remove', function (imageInput) {
                swal.fire({
                    title: 'Image successfully removed !',
                    type: 'error',
                    buttonsStyling: false,
                    confirmButtonText: 'Got it!',
                    confirmButtonClass: 'btn btn-primary font-weight-bold'
                });
            });
        </script>

    @endpush

</x-dashboard.layout>

resources/views/dashboard/managers/index.blade.php
<x-dashboard.layout>

    @push('styles')
        <!--begin::Page Vendors Styles(used by this page)-->
        <link href="{{asset('dashboard/assets/plugins/custom/datatables/datatables.bundle.css')}}"
              rel="stylesheet"
              type="text/css"/>
        <!--end::Page Vendors Styles-->
    @endpush

    <!--begin::Subheader-->
    <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
        <div
            class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::Info-->
            <div class="d-flex align-items-center flex-wrap mr-2">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">الادارة</h5>
                <!--end::Page Title-->
                <!--begin::Actions-->
                <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>

                <!--end::Actions-->
            </div>
            <!--end::Info-->

        </div>
    </div>
    <!--end::Subheader-->

    <x-dashboard.wrap>

        <!--begin::Card-->
        <div class="card">
            <div class="card-header flex-wrap border-0 pt-6 pb-0">

                <div class="card-toolbar">

                    <!--begin::Button-->
                    <a href="{{route('managers.create')}}"
                       class="btn btn-primary font-weight-bolder">
											<span class="svg-icon svg-icon-md">
												<!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
												<svg xmlns="http://www.w3.org/2000/svg"
                                                     xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                                     height="24px" viewBox="0 0 24 24" version="1.1">
													<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
														<rect x="0" y="0" width="24" height="24"/>
														<circle fill="#000000" cx="9" cy="15" r="6"/>
														<path
                                                            d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z"
                                                            fill="#000000" opacity="0.3"/>
													</g>
												</svg>
                                                <!--end::Svg Icon-->
											</span>مدير جديد</a>
                    <!--end::Button-->
                </div>
            </div>
            <div class="card-body">
                <!--begin: Datatable-->
                <table class="table table-separate"
                       id="kt_datatable">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>الصوره</th>
                        <th>الأسم المستخدم</th>
                        <th>الجوال</th>
                        {{--                        <th>الحالة</th>--}}
                        <th>الأكشن</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($managers as $manager)
                        <tr>
                            <td>{{$manager->id}}</td>
                            <td>
                                <div class="symbol symbol-70">
                                    <img class=""
                                         src="{{$manager->avatar ? asset('storage/'.$manager->avatar) : asset('dashboard/assets/media/users/blank.png') }}">
                                </div>
                            </td>
                            <td>{{$manager->username}}</td>
                            <td>{{$manager->phone}}</td>
                            {{--                        <td>{{$manager->phone}}</td>--}}
                            <td>
                                <a href="{{route('managers.show',$manager->id)}}/"
                                   class="btn btn-sm btn-clean btn-icon mr-2"
                                   title="Edit details">
                                    <span class="svg-icon svg-icon-md">
                                       <i class="icon-xl la la-eye"></i>
                                    </span>
                                </a>

                                <a href="{{route('managers.edit',$manager->id)}}"
                                   class="btn btn-sm btn-clean btn-icon mr-2"
                                   title="Edit details">
                                    <span class="svg-icon svg-icon-md">
                                       <i class="icon-xl la la-pencil-alt"></i>
                                    </span>
                                </a>

                                <form class="d-inline-flex"
                                      method="post"
                                      action="{{route('managers.destroy',$manager->id)}}">
                                    @csrf
                                    @method('delete')
                                    <button type="submit"
                                            id="kt_sweetalert_demo_9"
                                            class="btn btn-sm btn-clean btn-icon"
                                            title="Delete">
                                <span class="svg-icon svg-icon-md">
                                    <i class="icon-xl la la-trash-alt"></i>
                                </span>
                                    </button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <!--end: Datatable-->
            </div>
        </div>
        <!--end::Card-->

    </x-dashboard.wrap>

    @push('scripts')
        <script src="{{asset('dashboard/assets/plugins/custom/datatables/datatables.bundle.js')}}"></script>
        <script src="{{asset('dashboard/assets/js/pages/features/miscellaneous/sweetalert2.js')}}"></script>

        <script>
            jQuery(document).ready(function () {
                $('#kt_datatable').DataTable({
                    pagingType: 'full_numbers',
                    scrollY: 500,
                    scrollX: true,
                    paging: true,
                    // lengthMenu: [
                    //     [10, 25, 50, -1],
                    //     [10, 25, 50, 'All'],
                    // ],
                    language: {
                        url: 'https://cdn.datatables.net/plug-ins/1.11.5/i18n/ar.json',
                    },
                });


                $("#kt_sweetalert_demo_9").click(function (e) {
                    var form = $(this).closest("form");
                    var name = $(this).data("name");
                    event.preventDefault();
                    Swal.fire({
                        title: "Are you sure?",
                        text: "You won't be able to revert this!",
                        icon: "warning",
                        showCancelButton: true,
                        confirmButtonText: "Yes, delete it!",
                        customClass: {
                            confirmButton: "btn btn-danger",
                            cancelButton: "btn btn-light-primary"
                        }
                    }).then(function (result) {
                        if (result.value) {
                            Swal.fire(
                                "Deleted!",
                                "Your file has been deleted.",
                                "success"
                            )
                            form.submit()
                        }
                    });
                });


            });
        </script>
    @endpush

</x-dashboard.layout>